name: 'Npm cache'
description: 'Cache npm dependencies'
inputs:
  hash:
    description: hash of package.lock
    required: true
runs:
  using: 'node12'
  main: 'restore/index.js'
  post: 'save/index.js'
