name: Comment on Pull Request

on:
  pull_request:
    paths:
      - 'pr-comment/**'

env:
  CI: true

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./pr-comment/
        with:
          header: FromPR
          recreate: true
          message: |
            Test ${{ github.sha }} is successfully ended.
            This is message from PR.
      - uses: ./pr-comment/
        with:
          header: FromPR
          append: true
          message: |
            Append message.