name: Publish lib to NPM

on:
  workflow_call:
    inputs:
      BUILD_ARTIFACT_NAME:
        required: true
        type: string
      PATH_TO_ARTIFACT:
        required: false
        type: string
        default: ./ # by default we upload the artifact on the root directory

jobs:
# ---------------------------------------------------------------- 
# ------------------------- NPM PUBLISH --------------------------
# ----------------------------------------------------------------
  Publish: 
    name: Publish to NPM 
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.BUILD_ARTIFACT_NAME }}
          path: ${{ inputs.PATH_TO_ARTIFACT }}
      
      - name: publish 
        shell: bash
        run: |
          export NPM_TOKEN=${{ env.NPM_TOKEN }}
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          if ${{ !startsWith(github.ref, 'refs/tags/') }}; then
            npm version prerelease --git-tag-version false --preid=${{ github.sha }}
          fi
          npm publish