name: Test Summary

on:
  pull_request:
    paths:
      - 'test-summary/**'

env:
  CI: true

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./test-summary/
        with:
          path: './test-summary/test/'

      - name: Tests
        run: |
          test ${{ env.numPassedTestSuites }} -eq 348 -a ${{ env.numFailedTestSuites }} -eq 0 -a ${{ env.numTotalTestSuites }} -eq 348 -a ${{ env.numPassedTests }} -eq 1535 -a ${{ env.numFailedTests }} -eq 0 -a ${{ env.numTotalTests }} -eq 1541

      - name: Coverage file
        run: |
          [ -s coverage-final.json ]
